/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShowsImport } from './routes/shows'
import { Route as MoviesImport } from './routes/movies'
import { Route as LoginImport } from './routes/login'
import { Route as BrowseImport } from './routes/browse'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShowsRoute = ShowsImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRoute,
} as any)

const MoviesRoute = MoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BrowseRoute = BrowseImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/login' | '/movies' | '/shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/login' | '/movies' | '/shows'
  id: '__root__' | '/' | '/browse' | '/login' | '/movies' | '/shows'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  ShowsRoute: typeof ShowsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  ShowsRoute: ShowsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/browse",
        "/login",
        "/movies",
        "/shows"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/browse": {
      "filePath": "browse.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/movies": {
      "filePath": "movies.tsx"
    },
    "/shows": {
      "filePath": "shows.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
